name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v3 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Setup Node # 步骤2
        uses: actions/setup-node@v3 # 安装node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Build # 步骤3
        run: npm install && npm run build # 构建文件
      - name: Build and Deploy # 步骤4
        uses: JamesIves/github-pages-deploy-action@v4.2.5 # 作用：部署到gitpages
        with:
          repository-name: esqbs/blog-pub # 部署仓库名
          token: ${{ secrets.BLOG_TOKEN }} # toKen私密变量
          branch: gh-pages # 部署到的分支
          folder: docs/.vuepress/dist # 要部署的文件夹.
          clean: true
